export default [
  { name: 'Intro', time: 1, tags:'asd sdfsfd'},
  { name: 'Υποφέρω', time: 62, tags: 'mpla' },
  { name: 'Enter Sandman Riff 1', time: 90, tags: 'mpla'},
  { name: 'Είναι μια καμήλα', time: 105, tags: 'mpla'},
  { name: 'Enter Sandman Riff 2', time: 120, tags: 'mpla'},
  { name: 'Αμάρτησε μαζί μου', time: 128, tags: 'mpla'},
  { name: 'Dimitris Dragon (guitar solo)', time: 158, tags: 'magalios κούκου' },
  { name: 'Enter Sandman Riff 3', time: 175, tags: 'mpla'},
  { name: 'Βρε μελαχρινάκι', time: 183, tags: 'mpla'},
  { name: 'Enter Sandman Riff 4', time: 199, tags: 'mpla'},
  { name: 'Καταιγίδα', time: 206, tags: 'mpla'},
  { name: 'Enter Sandman Riff 5', time: 246, tags:'asd sdfsfd xxx'},
  { name: 'Γυμνός μεσ\'την Ελλάδα', time: 254, tags: 'mpla'},
  { name: 'Enter Sandman Riff 6', time: 270, tags: 'mpla'},
  { name: 'Κατάλληλες προϋποθέσεις', time: 277, tags: 'mpla'},
  { name: 'Nikos Nikolaou (guitar solo)', time: 303.6, tags: 'mpla'},
  { name: 'Enter Sandman Riff 7', time: 330.4, tags: 'mpla'},
  { name: 'Ρίξε στο κορμί μου σπίρτο', time: 338, tags: 'mpla'},
  { name: 'Enter Sandman Riff 8', time: 330.5, tags: 'mpla'},
  { name: 'Το κάτι που θέλω', time: 359, tags: 'mpla'},
  { name: 'Enter Sandman Riff 9', time: 375.4, tags: 'mpla'},
  { name: 'Gucci φόρεμα', time: 383, tags: 'mpla'},
  { name: 'Crazy train Riff', time: 414, tags: 'mpla'},
  { name: 'Ψίθυροι καρδιάς', time: 429, tags: 'mpla'},
  { name: 'Enter Sandman Riff 10', time: 460, tags: 'mpla'},
  { name: 'Τα μαύρα εσώρουχα', time: 468, tags: 'mpla'},
  { name: 'Enter Sandman Riff 11', time: 492.8, tags: 'mpla'},
  { name: 'Αχ κορίτσι μου', time: 507.8, tags: 'mpla'},
  { name: 'Skapator (guitar solo)', time: 536, tags: 'mpla'},
  { name: 'Τσάι με λεμόνι', time: 566, tags: 'mpla'},
  { name: 'Smoke on the water Μπουζούκι Riff', time: 581.4, tags: 'mpla'},
  { name: 'Μωρό μου σόρρυ', time: 588, tags: 'mpla'},
  { name: 'Enter Sandman Riff 12', time: 622, tags: 'mpla'},
  { name: 'Ξέρω τι ζητάω', time: 629.3, tags: 'mpla'},
  { name: 'Νεκροπεθαμένος (guitar solo)', time: 661, tags: 'mpla'},
  { name: 'Enter Sandman Riff 12', time: 701, tags: 'mpla'},
  { name: 'Gigi', time: 708.4, tags: 'mpla'},
  { name: 'Enter Sandman Riff 13', time: 724, tags: 'mpla'},
  { name: 'Η αγάπη βλάπτει σοβαρά', time: 739, tags: 'mpla'},
  { name: 'Jens Ludwig (guitar solo)', time: 761.2, tags: 'mpla'},
  { name: 'Έλα μου', time: 793, tags: 'mpla'},
  { name: 'Enter Sandman Riff 14', time: 809, tags: 'mpla'},
  { name: 'Mε λένε Πόπη/Painkiller/Σαϊτιά', time: 824, tags: 'mpla'},
  { name: 'Enter Sandman Riff 15', time: 850.1, tags: 'mpla'},
  { name: 'Δεν γίνετε', time: 864.7, tags: 'mpla'},
  { name: 'Enter Sandman Riff 15', time: 881, tags: 'mpla'},
  { name: 'Κορίτσι του Μάη', time: 894.6, tags: 'mpla'},
  { name: 'Enter Sandman Riff 16', time: 918, tags: 'mpla'},
  { name: 'Πίπα της Ειρήνης', time: 931, tags: 'mpla'},
  { name: 'Iron man (Μπουζουκι riff)', time: 962, tags: 'mpla'},
  { name: 'Ποιά θυσία', time: 978, tags: 'mpla'},
  { name: 'Enter Sandman Riff 17', time: 1001, tags: 'mpla'},
  { name: 'Σαν να μπαίνει η Άνοιξη', time: 1017, tags: 'mpla'},
  { name: 'Lightnin Boy (guitar solo)', time: 1033, tags: 'mpla'},
  { name: 'Enter Sandman Riff 18', time: 1049, tags: 'mpla'},
  { name: 'Μην παραχαράσετε την ιστορία', time: 1063, tags: 'mpla'},
  { name: 'Enter Sandman Riff 19', time: 1079, tags: 'mpla'},
  { name: 'Η καρδιά μου χτυπά', time: 1095, tags: 'mpla'},
  { name: 'Enter Sandman Riff 20', time: 1118, tags: 'mpla'},
  { name: 'Δοκιμασέ με', time: 1133, tags: 'mpla'},
  { name: 'Enter Sandman Riff 21', time: 1149, tags: 'mpla'},
  { name: 'Ζιγκολό', time: 1164, tags: 'mpla'},
  { name: 'Μάριος Μπουνίκας (guitar solo)', time: 1185.8, tags: 'mpla'},
  { name: 'Killing in the name (Μπουζουκι solo)', time: 1208, tags: 'mpla'},
  { name: 'Σοκολάτα', time: 1231, tags: 'mpla'},
  { name: 'Αντώνης Χριστοδουλάκης (Κeys solo)', time: 1246, tags: 'mpla'},
  { name: 'Enter Sandman Riff 22', time: 1263, tags: 'mpla'},
  { name: 'Mαγικά χαλιά', time: 1277, tags: 'mpla'},
  { name: 'Enter Sandman Riff 23', time: 1293, tags: 'mpla'},
  { name: 'Καγκέλια', time: 1306.6, tags: 'mpla'},
  { name: 'The final countdown (with μπουζούκι)', time: 1323.8, tags: 'mpla'},
  { name: 'Outro', time: 1377, tags: 'mpla'},
];
